### ISSUE TITLE
configparser.NoSectionError: No section: 'Settings'

### ISSUE THREAD

**Issue by jaffe-fly** [levipereira/deepstream-yolo-e2e#14]
```
Please choose the output option:
+-------+---------------+--------------------------+
| Index | Output Option | Description              |
+-------+---------------+--------------------------+
| 1     | display       | Output to display window |
| 2     | file          | Save output to a file    |
| 3     | rtsp          | Stream output via RTSP   |
| 4     | silent        | No output                |
+-------+---------------+--------------------------+
Enter the number corresponding to your choice: 1
Previous configuration found.

Active Media Sources:
+-------------------------+------------+-------------------------------------------------------------------------+---------+
| Media Name              | Media Type | URL                                                                     | Status  |
+-------------------------+------------+-------------------------------------------------------------------------+---------+
| Deepstream Sample 1024p | file       | /opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4 | Enabled |
+-------------------------+------------+-------------------------------------------------------------------------+---------+
Do you want to modify the media source? [Enter to continue or m to modify]: 

Previous Model Configuration:
+------------+-------------+
| Model Type | Model Name  |
+------------+-------------+
| Detection  | yolov8x-trt |
+------------+-------------+
Do you want to modify the model? [Enter to continue or m to modify]:
Success: Configuration saved.
Warning: The engine file '/apps/deepstream-yolo-e2e/models/engine/yolov8x-trt-fp16-netsize-640-batch-1.engine' already exists and will be reused. Use --force to rebuild.
PGIE Configuration file 'config/pgie/config_pgie_yolo_det.txt' updated.
Traceback (most recent call last):
  File "/tmp/deepstream-yolo-e2e/deepstream.py", line 88, in <module>
    sys.exit(run_pipeline(args))
  File "/tmp/deepstream-yolo-e2e/python_module/component/pipeline.py", line 255, in run_pipeline
    model_type = pre_process(args.output)
  File "/tmp/deepstream-yolo-e2e/python_module/component/pre_process.py", line 147, in pre_process
    show_current_resolution()
  File "/tmp/deepstream-yolo-e2e/python_module/component/system_config.py", line 49, in show_current_resolution
    resolution = f"{config.getint('Settings', 'tiled_output_width')} x {config.getint('Settings', 'tiled_output_height')}"
  File "/usr/lib/python3.10/configparser.py", line 820, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 810, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 805, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.10/configparser.py", line 783, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.10/configparser.py", line 1154, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
```
more `config/pgie/config_pgie_yolo_det.txt`

```
[property]
gpu-id=0
net-scale-factor=0.0039215697906911373
model-color-format=0
onnx-file=/tmp/deepstream-yolo-e2e/models/onnx/yolov8x-trt.onnx
model-engine-file=/apps/deepstream-yolo-e2e/models/engine/yolov8x-trt-fp16-netsize-640-batch-1.engine
labelfile-path=/tmp/deepstream-yolo-e2e/models/onnx/yolov8x-trt.txt
batch-size=1
infer-dims=3;640;640
force-implicit-batch-dim=0
# 0: FP32 1: INT8 2: FP16
network-mode=2
num-detected-classes=80
interval=0
gie-unique-id=1
process-mode=1
# 0: Detector 1: Classifier 2: Segmentation 3: Instance Segmentation
network-type=0
cluster-mode=2
maintain-aspect-ratio=1
parse-bbox-func-name=NvDsInferYoloNMS
custom-lib-path=/opt/nvidia/deepstream/deepstream/lib/libnvds_infer_yolo.so

[class-attrs-all]
pre-cluster-threshold=0.25
```

**Comment by levipereira** [comment]
I tested each step and didn’t encounter any issues. Could you let me know the specific steps you followed?
```bash
Please choose the output option:
+-------+---------------+--------------------------+
| Index | Output Option | Description              |
+-------+---------------+--------------------------+
| 1     | display       | Output to display window |
| 2     | file          | Save output to a file    |
| 3     | rtsp          | Stream output via RTSP   |
| 4     | silent        | No output                |
+-------+---------------+--------------------------+
Enter the number corresponding to your choice: 1
Warning: No previous configuration found. Please configure now.
Media Summary:
+----------+-------+
|  Status  | Count |
+----------+-------+
|  Active  |   1   |
| Inactive |   12  |
+----------+-------+

Menu:
+-------+------------------+
| Index | Option           |
+-------+------------------+
|   1   | Activate Media   |
|   2   | Deactivate Media |
|   3   | List Media       |
|   4   | Add Media        |
|   5   | Remove Media     |
|   0   | Finish           |
+-------+------------------+
Select an option: 0

Choose a Dataset (or enter '0' to exit):
+-------+-----------+-----------------------------------------------------------------+
| Index | Dataset   | Description                                                     |
+-------+-----------+-----------------------------------------------------------------+
|   1   | COCO      | COCO dataset is a large-scale object detection and segmentation |
|   2   | WIDERFace | WIDER FACE dataset is a face detection dataset                  |
+-------+-----------+-----------------------------------------------------------------+
Enter your choice: 1

You chose: COCO

Choose Model Type:
+-------+--------------+
| Index | Option       |
+-------+--------------+
|   1   | Detection    |
|   2   | Segmentation |
+-------+--------------+
Enter your choice (or '0' to go back): 1

You chose: Detection

Choose Size:
+-------+-------------+
| Index | Option      |
+-------+-------------+
|   1   | Nano        |
|   2   | Small       |
|   3   | Medium      |
|   4   | Balanced    |
|   5   | Large       |
|   6   | Extra-large |
+-------+-------------+
Enter your choice (or '0' to go back): 6

You chose: Extra-large

Available Models:
+-------+------------+--------------+
| Index | Model Arch | Model Name   |
+-------+------------+--------------+
|   1   | YOLOv8     | yolov8x-trt  |
|   2   | YOLOv9     | yolov9e-trt  |
|   3   | YOLOv10    | yolov10x-trt |
|   4   | YOLO11     | yolo11x-trt  |
+-------+------------+--------------+

Enter the index of the model you want to download (or '0' to go back): 1
Downloading models/onnx/yolov8x-trt.onnx: 100.00%
Downloaded: models/onnx/yolov8x-trt.onnx
Downloading models/onnx/yolov8x-trt.txt: 100.00%
Downloaded: models/onnx/yolov8x-trt.txt
Model downloaded to: models/onnx/yolov8x-trt.onnx
Label file downloaded to: models/onnx/yolov8x-trt.txt
Exiting the application after downloading the model.
Success: Configuration saved.
PGIE Configuration file 'config/pgie/config_pgie_yolo_det.txt' updated.
+-------------------+
| Output Resolution |
+-------------------+
|     1280 x 720    |
+-------------------+
Do you want to modify current output resolution? [Enter to continue or m to modify]:

(gst-plugin-scanner:4066): GStreamer-WARNING **: 23:17:59.473: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstpulseaudio.so': libFLAC.so.8: cannot open shared object file: No such file or directory
0:00:00.004522900  4072 0x55de5f3718f0 ERROR     GST_PLUGIN_LOADING gstpluginloader.c:1161:exchange_packets: write fd 0 errored
0:00:00.791053860  3280 0x5588bb57e180 ERROR     GST_PLUGIN_LOADING gstpluginloader.c:279:plugin_loader_replay_pending: Plugin file /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmsdk.so failed to load. Blacklisting

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.543: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstfluidsynthmidi.so': libFLAC.so.8: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.548: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstfaad.so': libfaad.so.2: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.561: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstflac.so': libFLAC.so.8: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.574: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmpeg2enc.so': libmjpegutils-2.1.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.579: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so': libmp3lame.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.584: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstsndfile.so': libFLAC.so.8: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.589: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvoaacenc.so': libvo-aacenc.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.593: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstopenh264.so': libopenh264.so.6: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.600: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlame.so': libmp3lame.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.623: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstmplex.so': libmjpegutils-2.1.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.635: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstchromaprint.so': libmp3lame.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:4073): GStreamer-WARNING **: 23:17:59.835: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_udp.so': librivermax.so.1: cannot open shared object file: No such file or directory
[youtube] Extracting URL: https://www.youtube.com/watch?v=ByED80IKdIU
[youtube] ByED80IKdIU: Downloading webpage
[youtube] ByED80IKdIU: Downloading ios player API JSON
[youtube] ByED80IKdIU: Downloading mweb player API JSON
[youtube] ByED80IKdIU: Downloading m3u8 information
[youtube] ByED80IKdIU: Downloading m3u8 information
Source: https://www.youtube.com/watch?v=ByED80IKdIU. Creating source_bin 0

Creating source bin
source-bin-00
Starting pipeline

gstnvtracker: Loading low-level lib at /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
[NvMultiObjectTracker] Initialized
0:00:03.609243292  3280 0x5588bb57e180 INFO                 nvinfer gstnvinfer.cpp:684:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:2092> [UID = 1]: deserialized trt engine from :/apps/deepstream-yolo-e2e/models/engine/yolov8x-trt-fp16-netsize-640-batch-1.engine
Implicit layer support has been deprecated
INFO: ../nvdsinfer/nvdsinfer_model_builder.cpp:327 [Implicit Engine Info]: layers num: 0

0:00:03.609289692  3280 0x5588bb57e180 INFO                 nvinfer gstnvinfer.cpp:684:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2195> [UID = 1]: Use deserialized engine model: /apps/deepstream-yolo-e2e/models/engine/yolov8x-trt-fp16-netsize-640-batch-1.engine
0:00:03.614286293  3280 0x5588bb57e180 INFO                 nvinfer gstnvinfer_impl.cpp:343:notifyLoadModelStatus:<primary-inference> [UID 1]: Load new model:/apps/deepstream-yolo-e2e/config/pgie/config_pgie_yolo_det.txt sucessfully
Decodebin child added: source

Decodebin child added: typefindelement0

Decodebin child added: decodebin0

Decodebin child added: hlsdemux0

Decodebin child added: multiqueue0

Decodebin child added: tsdemux0

Decodebin child added: multiqueue1

Decodebin child added: h264parse0

Decodebin child added: capsfilter0

Decodebin child added: nvv4l2decoder0

Failed to query video capabilities: Inappropriate ioctl for device
In cb_newpad

gstname= video/x-raw
features= <Gst.CapsFeatures object at 0x7fcf179d1fc0 (GstCapsFeatures at 0x7fce600cebd0)>

(python3:3280): GStreamer-CRITICAL **: 23:18:04.769: gst_query_set_context: assertion 'strcmp (gst_context_get_context_type (context), context_type) == 0' failed

(python3:3280): GStreamer-CRITICAL **: 23:18:04.769: gst_element_set_context: assertion 'GST_IS_CONTEXT (context)' failed

(python3:3280): GStreamer-CRITICAL **: 23:18:05.185: gst_query_set_context: assertion 'strcmp (gst_context_get_context_type (context), context_type) == 0' failed

(python3:3280): GStreamer-CRITICAL **: 23:18:05.185: gst_element_set_context: assertion 'GST_IS_CONTEXT (context)' failed

**PERF:  {'stream0': 24.47}


(python3:3280): GStreamer-CRITICAL **: 23:18:08.733: gst_query_set_context: assertion 'strcmp (gst_context_get_context_type (context), context_type) == 0' failed

(python3:3280): GStreamer-CRITICAL **: 23:18:08.733: gst_element_set_context: assertion 'GST_IS_CONTEXT (context)' failed
root@Levi-PC:/apps/deepstream-yolo-e2e#
```

**Comment by jaffe-fly** [comment]
```
root@ps:/tmp/deepstream-yolo-e2e# ./deepstream.py 
Please choose the output option:
+-------+---------------+--------------------------+
| Index | Output Option | Description              |
+-------+---------------+--------------------------+
| 1     | display       | Output to display window |
| 2     | file          | Save output to a file    |
| 3     | rtsp          | Stream output via RTSP   |
| 4     | silent        | No output                |
+-------+---------------+--------------------------+
Enter the number corresponding to your choice: 1
Warning: No previous configuration found. Please configure now.
Media Summary:
+----------+-------+
|  Status  | Count |
+----------+-------+
|  Active  |   1   |
| Inactive |   12  |
+----------+-------+

Menu:
+-------+------------------+
| Index | Option           |
+-------+------------------+
|   1   | Activate Media   |
|   2   | Deactivate Media |
|   3   | List Media       |
|   4   | Add Media        |
|   5   | Remove Media     |
|   0   | Finish           |
+-------+------------------+
Select an option: 0

Choose a Dataset (or enter '0' to exit):
+-------+-----------+-----------------------------------------------------------------+
| Index | Dataset   | Description                                                     |
+-------+-----------+-----------------------------------------------------------------+
|   1   | COCO      | COCO dataset is a large-scale object detection and segmentation |
|   2   | WIDERFace | WIDER FACE dataset is a face detection dataset                  |
+-------+-----------+-----------------------------------------------------------------+
Enter your choice: 1

You chose: COCO

Choose Model Type:
+-------+--------------+
| Index | Option       |
+-------+--------------+
|   1   | Detection    |
|   2   | Segmentation |
+-------+--------------+
Enter your choice (or '0' to go back): 1

You chose: Detection

Choose Size:
+-------+-------------+
| Index | Option      |
+-------+-------------+
|   1   | Nano        |
|   2   | Small       |
|   3   | Medium      |
|   4   | Balanced    |
|   5   | Large       |
|   6   | Extra-large |
+-------+-------------+
Enter your choice (or '0' to go back): 6

You chose: Extra-large

Available Models:
+-------+------------+--------------+
| Index | Model Arch | Model Name   |
+-------+------------+--------------+
|   1   | YOLOv8     | yolov8x-trt  |
|   2   | YOLOv9     | yolov9e-trt  |
|   3   | YOLOv10    | yolov10x-trt |
|   4   | YOLO11     | yolo11x-trt  |
+-------+------------+--------------+

Enter the index of the model you want to download (or '0' to go back): 1
yolov8x-trt.onnx already exists, skipping download.
yolov8x-trt.txt already exists, skipping download.
Model downloaded to: models/onnx/yolov8x-trt.onnx
Label file downloaded to: models/onnx/yolov8x-trt.txt
Exiting the application after downloading the model.
Success: Configuration saved.
Warning: The engine file '/apps/deepstream-yolo-e2e/models/engine/yolov8x-trt-fp16-netsize-640-batch-1.engine' already exists and will be reused. Use --force to rebuild.
PGIE Configuration file 'config/pgie/config_pgie_yolo_det.txt' updated.
Traceback (most recent call last):
  File "/tmp/deepstream-yolo-e2e/./deepstream.py", line 88, in <module>
    sys.exit(run_pipeline(args))
  File "/tmp/deepstream-yolo-e2e/python_module/component/pipeline.py", line 255, in run_pipeline
    model_type = pre_process(args.output)
  File "/tmp/deepstream-yolo-e2e/python_module/component/pre_process.py", line 147, in pre_process
    show_current_resolution()
  File "/tmp/deepstream-yolo-e2e/python_module/component/system_config.py", line 49, in show_current_resolution
    resolution = f"{config.getint('Settings', 'tiled_output_width')} x {config.getint('Settings', 'tiled_output_height')}"
  File "/usr/lib/python3.10/configparser.py", line 820, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 810, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 805, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.10/configparser.py", line 783, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.10/configparser.py", line 1154, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Settings'
```
compare with you,no this section
```
Success: Configuration saved.
PGIE Configuration file 'config/pgie/config_pgie_yolo_det.txt' updated.
+-------------------+
| Output Resolution |
+-------------------+
|     1280 x 720    |
+-------------------+
```

**Comment by jaffe-fly** [comment]
should update you config file path  https://github.com/levipereira/deepstream-yolo-e2e/blob/9f8b6ef19605655adc6fde4e1850b1ddcfa9407d/python_module/component/system_config.py#L4

**Comment by levipereira** [comment]
Are you using the latest commit from the master branch?
